---
name: 🐛 バグ報告
about: システムの不具合・エラーを報告する際に使用
title: '[BUG] '
labels: ['bug', 'needs-investigation']
assignees: ''
---

## 🐛 バグ概要

### 📋 問題の詳細
<!-- 何が起きているか、簡潔に記述 -->

### 🔄 再現手順
1. 
2. 
3. 
4. 

### 📊 期待される動作
<!-- 本来どのように動作すべきか -->

### 📊 実際の動作
<!-- 実際にどのような動作をしているか -->

### 📷 スクリーンショット・ログ
<!-- 可能であれば、スクリーンショットやエラーログを添付 -->

---

## 🖥️ 環境情報

### 💻 システム環境
- **OS**: 
- **ブラウザ**: 
- **Python版**: 
- **その他**: 

### 📦 関連コンポーネント
- [ ] 🤖 AIチャット (gra_01_chat)
- [ ] 📁 ファイル管理 (gra_05_files)  
- [ ] 🎯 GitHub Issue自動生成 (gra_03_programfromdocs)
- [ ] 🌐 HTML表示 (gra_07_html)
- [ ] 🔧 OpenInterpreter (gra_09_openinterpreter)
- [ ] 🧠 記憶復元 (gra_15_memory_restore)
- [ ] 📊 GitHub Issueシステム生成 (gra_github_issue_generator)
- [ ] 📈 システム監視 (gra_11_system_monitor)
- [ ] 🌐 API基盤 (routes/api.py)
- [ ] 🔧 その他

---

## 🚨 緊急度・影響度

### 📊 緊急度
- [ ] 🔥 緊急（システム停止）
- [ ] ⚡ 高（主要機能不具合）
- [ ] 📋 中（一部機能不具合）
- [ ] 💭 低（軽微な問題）

### 👥 影響範囲
- [ ] 🌍 全ユーザー
- [ ] 👥 特定機能利用者
- [ ] 👤 個人環境のみ

---

## 🔍 調査情報

### 🧪 テスト実行結果
<!-- AUTOCREATE_System_Test_Guide.ipynb のテスト結果があれば -->

### 📊 ログ・エラー情報
```
<!-- エラーログやコンソール出力をここに貼り付け -->
```

### 🔧 試した対処法
<!-- 既に試した解決方法があれば -->

---

**📝 補足・その他**
<!-- その他特記事項があれば -->
