---
name: 🤝 AI協働開発相談
about: 人間・AI協働での開発相談・ディスカッション
title: '[COLLABORATION] '
labels: ['discussion', 'ai-collaboration', 'brainstorming']
assignees: ''
---

## 🤝 協働開発相談・ディスカッション

### 💭 相談内容・テーマ
<!-- 何について相談・議論したいか -->

### 🎯 目的・ゴール
<!-- この相談を通じて何を達成したいか -->

### 🤔 現在の状況・課題
<!-- 現在どのような状況で、どんな課題があるか -->

---

## 👥 協働の観点

### 👤 人間側の視点・アイデア
<!-- 人間側からの視点、アイデア、懸念事項など -->

### 🤖 AI側に求める視点・支援
<!-- AIにどのような視点・支援を求めるか -->

### 🎨 創造性・革新性の要素
<!-- 創造的・革新的な要素があるか -->

---

## 📊 技術的考慮事項

### 🏗️ 技術的制約・要件
<!-- 技術的な制約や要件があるか -->

### 🔗 既存システムとの関係
<!-- 既存のシステム・機能との関係性 -->

### 📈 拡張性・将来性
<!-- 将来の拡張可能性について -->

---

## 🎯 期待する成果

### ✅ 具体的な成果物
<!-- どのような成果物が欲しいか -->

### 📅 タイムライン
<!-- いつまでに結論・実装が必要か -->

### 🎓 学習・改善ポイント
<!-- この協働を通じて学びたいこと -->

---

## 🌟 その他

### 💡 参考情報・リンク
<!-- 参考になる情報やリンクがあれば -->

### 🎨 イメージ・アイデアスケッチ
<!-- 画像やイメージがあれば添付 -->

---

**🤝 協働開発パートナーとして、建設的な議論を期待しています！**
