---
name: 🚀 機能要求・アイデア提案
about: 新機能のアイデアや改善提案を行う際に使用
title: '[FEATURE] '
labels: ['enhancement', 'ai-collaboration', 'feature-request']
assignees: ''
---

## 💡 機能アイデア・要求概要

### 🎯 実現したいこと
<!-- 何を実現したいか、簡潔に記述 -->

### 🌟 背景・動機  
<!-- なぜこの機能が必要なのか、どんな問題を解決するのか -->

### 📝 詳細な要求仕様
<!-- 具体的にどのように動作すべきか -->

### ✅ 受け入れ条件（Definition of Done）
- [ ] 機能が正常に動作する
- [ ] テストが通る
- [ ] ドキュメントが更新される
- [ ] システム全体との整合性が確認される
- [ ] 

### 🤖 AI実装方針・技術アプローチ
<!-- AI側でどのような技術的アプローチを取るか -->

### 👤 人間側責任範囲
<!-- 人間側で担当・決定すべき部分 -->

### 🎨 UI/UX要求
<!-- インターフェースに関する要求があれば -->

### 📊 優先度
- [ ] 🔥 緊急（1週間以内）
- [ ] ⚡ 高（1ヶ月以内）
- [ ] 📋 中（3ヶ月以内）
- [ ] 💭 低（将来的に）

### 🔗 関連情報
<!-- 関連するIssue、PR、ドキュメントなどがあれば -->

---

## 🤝 協働開発計画

### 👥 担当者・ロール分担
- **👤 人間パートナー**: 
- **🤖 AIパートナー**: 

### 📅 予想開発期間
<!-- 実装にかかりそうな時間の見積もり -->

### 🧪 テスト計画
<!-- どのようなテストを行うか -->

---

**📝 補足・その他**
<!-- その他特記事項があれば -->
