version: '3.8'

services:
  # 🐘 PHP Laravel Application
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: laravel_app_trudtdock
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./docker/app/php.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=laravel_db
      - DB_USERNAME=laravel_user
      - DB_PASSWORD=laravel_password
    networks:
      - laravel_network
    depends_on:
      - mysql

  # 🌐 Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: nginx_trudtdock
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_network
    depends_on:
      - app

  # 🐬 MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mysql_trudtdock
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - laravel_network

  # 📊 phpMyAdmin
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_trudtdock
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: laravel_user
      PMA_PASSWORD: laravel_password
    networks:
      - laravel_network
    depends_on:
      - mysql

  # 📧 Redis Cache (Optional)
  redis:
    image: redis:alpine
    container_name: redis_trudtdock
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
